name: Node CI

on: [push]

jobs:
  compile:

    runs-on: Agent-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '23'

      - name: Frontend compilation check 
        run: |
          cd client
          find . -name "*.js" -exec node --check {} +
      - name: Backend compilation check 
        run: |
          cd api 
          find . -name "*.js" -exec node --check {} +
  gitleaks-scan:
    runs-on: Agent-1
    needs: compile    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Create temp dir
        run: mkdir -p tmp

      - name: git-leaks setup
        uses: gitleaks/gitleaks-action@v2
        env:
         TMPDIR: ${{ github.workspace }}/tmp
      
      - name: Gitleaks scan
        run: |
          gitleaks detect --source ./client --exit-code 1
          gitleaks detect --source ./api --exit-code 1
       
  trivy-fs-scan:
    runs-on: Agent-1
    needs: gitleaks-scan
    steps: 
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Trivy FS scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH' 

  sonarqube-scan-backend:
    runs-on: Agent-1
    needs: trivy-fs-scan
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: SonarQube Scan api
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with: 
          projectBaseDir: ./api
          args: >
            -Dsonar.projectName=myorg
            -Dsonar.projectKey=myorg-key
  
  sonarqube-scan-frontend:
    runs-on: Agent-1
    needs: sonarqube-scan-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: SonarQube Scan client
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with: 
          projectBaseDir: ./api
          args: >
            -Dsonar.projectName=myorg
            -Dsonar.projectKey=myorg-key

  docker-backend: 
   runs-on: ubuntu-latest
   needs: sonarqube-scan-backend
   steps:
      
     -  name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
     -  name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
     -  name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
     -  name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: /api
          push: true
          tags: rajsingh8826/ds-backend:latest    


  docker-frontend: 
   runs-on: ubuntu-latest
   needs: sonarqube-scan-frontend
   steps:
      
     -  name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
     -  name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
     -  name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
     -  name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: /client
          push: true
          tags: rajsingh8826/ds-frontend:latest
          
            
            